### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by arichiardi** [Lambda-X/lambdax-web#47]
Like in `cljs-repl-web`, we can automagically generate it with a lot of online tools, but I need an icon that can suit small small icon size (32x32).

I don't think the one we have now would be visible.

**Comment by tomasz-biernacki** [comment]
Closed by https://github.com/Lambda-X/lambdax-web/commit/4cdd5d9cddd8c0fc3f3d0c109fd4e8d459a97625
